"use client"
import { useState } from "react"
import { useFormStatus } from "react-dom"
import { createExam, updateExam } from "@/app/admin/actions"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
function Submit({label}:{label:string}){const {pending}=useFormStatus();return <Button type="submit" disabled={pending}>{pending?"Saving…":label}</Button>}
export function ExamForm({exam}:{exam?:any}){const [pub,setPub]=useState(!!exam?.is_published);return <form action={exam?updateExam:createExam} className="space-y-5">{exam&&<input type="hidden" name="id" value={exam.id}/>}<div className="grid gap-5 md:grid-cols-2"><div className="space-y-2 md:col-span-2"><Label htmlFor="title">Exam title</Label><Input id="title" name="title" required defaultValue={exam?.title??""}/></div><div className="space-y-2 md:col-span-2"><Label htmlFor="description">Description</Label><Textarea id="description" name="description" defaultValue={exam?.description??""}/></div><div className="space-y-2"><Label htmlFor="subject">Subject</Label><Input id="subject" name="subject" defaultValue={exam?.subject??""}/></div><div className="space-y-2"><Label htmlFor="duration_minutes">Duration (minutes)</Label><Input id="duration_minutes" name="duration_minutes" type="number" min="1" max="600" defaultValue={exam?.duration_minutes??60}/></div><div className="space-y-2"><Label htmlFor="passing_score">Passing score (%)</Label><Input id="passing_score" name="passing_score" type="number" min="0" max="100" defaultValue={exam?.passing_score??50}/></div><label className="flex cursor-pointer items-center gap-3 rounded-xl border p-3"><input type="checkbox" name="is_published" checked={pub} onChange={e=>setPub(e.target.checked)} className="h-4 w-4"/><span><b className="block text-sm">Publish exam</b><span className="text-xs text-muted-foreground">Students can only take published exams.</span></span></label></div><div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={()=>history.back()}>Cancel</Button><Submit label={exam?"Save changes":"Create exam"}/></div></form>}
