"use client"
import { useFormStatus } from "react-dom"
import { createQuestion, updateQuestion } from "@/app/admin/actions"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { useState } from "react"
function Submit({label}:{label:string}){const {pending}=useFormStatus();return <Button type="submit" disabled={pending} className="w-full">{pending?"Saving…":label}</Button>}
export function QuestionForm({examId,question}:{examId:string;question?:any}){const [type,setType]=useState(question?.type??"mcq");const initial=(question?.options??[]).join("\n");return <form action={question?updateQuestion:createQuestion} className="space-y-4">{question&&<input type="hidden" name="id" value={question.id}/>}<input type="hidden" name="exam_id" value={examId}/><div className="space-y-2"><Label>Question type</Label><select name="type" value={type} onChange={e=>setType(e.target.value)} className="h-10 w-full rounded-lg border bg-background px-3 text-sm"><option value="mcq">Multiple choice</option><option value="true_false">True / False</option><option value="fill_blank">Fill in the blank</option></select></div><div className="space-y-2"><Label>Question</Label><Textarea name="question_text" required defaultValue={question?.question_text??""}/></div>{type==="mcq"&&<div className="space-y-2"><Label>Options (one per line)</Label><Textarea name="options_ui" defaultValue={initial} required placeholder={"Option A\nOption B\nOption C\nOption D"}/></div>}<input type="hidden" name="options" value={type==="mcq" ? JSON.stringify(initial.split("\n").map((x:string)=>x.trim()).filter(Boolean)) : "[]"} /><div className="space-y-2"><Label>Correct answer</Label><Input name="correct_answer" required defaultValue={question?.correct_answer??""} placeholder={type==="mcq"?"Exact option text":"Correct answer"}/></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Topic</Label><Input name="topic" defaultValue={question?.topic??""}/></div><div className="space-y-2"><Label>Points</Label><Input name="points" type="number" min="1" defaultValue={question?.points??1}/></div></div><div className="space-y-2"><Label>Subject (optional)</Label><Input name="subject" defaultValue={question?.subject??""}/></div><Submit label={question?"Save question":"Add question"}/></form>}
